[WIP]Added shutdown package to handle cailco-node shutdown
projectcalico/node pull request #993
Opened 2021-05-20 20:28 UTC by song-jiang

## Description

This PR added parameter to calico-node command to run shutdown process. The shutdown process involves
- Set node condition to "NetworkUnavailable=true", this would prevent pods been scheduled on the node.
- Write timestamp to a file that marks shutdown. This could be used by CNI plugins that calico-node is shutting down.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

2021-05-25 18:36 UTC, caseydavenport requested changes
Overall looks good! A few minor comments - mostly do we need the timestamp stuff?

2021-05-25 19:32 UTC, song-jiang commented on pkg/lifecycle/shutdown/shutdown.go
> +	_ = utils.SaveShutdownTimestamp()
I feel it is probably still useful to have timestamp written into the file. 
Startup.go would read timestamp, log it out and remove the file. So when user send us a calico-node log, it has the information when calico-node been shutdown previously (we can workout the time spent for calico-node pod restarting itself) or it is the first time calico node was running.

2021-05-26 17:43 UTC, caseydavenport approved these changes

2021-05-26 17:43 UTC, caseydavenport commented on pkg/lifecycle/shutdown/shutdown.go
> +	_ = utils.SaveShutdownTimestamp()
sgtm!

2021-05-26 20:15 UTC, merged